development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ENV['HEROKU_DATABASE']
  pool: 5
  username: ENV['HEROKU_USER']
  password: ENV['HEROKU_PW']

cucumber:
  <<: *TEST
