# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd09c489bd94871607cccea80abbb35698728a7b6fc3d28445e3cfaebe13993475319e1859a342a0b1e3f131895b4428db02620acaf005a69402c6b1656811b5

test:
  secret_key_base: 44a3e0ef3dd1a3e6eb23166ea805c64f5b75cce112b2dcf7988acc64c9a49cd180a0d153b379cf11121b3eef7174790655d5c3211cecb824a06233569abacbab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
